<?php echo $this->doctype() ?>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

	<head>

		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

		<title>
		
			MiniDirect
		
		</title>

        <?php 

            $this->headLink()->appendStylesheet('/css/bootstrap.min.css');

		    $this->headLink()->appendStylesheet('/css/global.less', null, null, array('rel'=>'stylesheet/less'));

		    $this->headScript()->offsetSetFile(-5, 'https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js');

		    $this->headScript()->offsetSetFile(-4, '/js/modernizr.custom.20456.js');

		    $this->headScript()->offsetSetFile(-3, '/js/less-1.3.1.min.js');

		    $this->headScript()->offsetSetFile(-2, '/js/bootstrap.min.js');

		    $this->headScript()->offsetSetFile(-1, '/js/global.js');

        ?>

        <?php echo $this->headLink() ?>

        <?php echo $this->headScript() ?>

        <script type="text/javascript">

            MINI.ServiceURL.AssessmentURL = "<?php echo $this->url(array('controller' => 'Patient', 'action' => 'getassessment')); ?>";

        </script>

	</head>

	<body>

		<div id="container" class="container">

			<div id="content">

				<div id="header" class="row">

					<div class="span12">

						<h3>
							
                            <a href="/">
                            
							    MiniDirect
                            
                            </a>

						</h3>

					</div>

				</div>

				<div id="navbar" class="navbar">

					<div class="navbar-inner">
				
						<ul class="nav">

                            <?php $controller = strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()); ?>
						
                            <li class="<?php echo $controller == "index" ? "active" : ""; ?>">

                                <a href="<?php echo $this->url(array('controller' => 'Index', 'action' => 'index')); ?>">

                                    For Patients

                                </a>

                            </li>

                            <li class="<?php echo $controller == "physician" ? "active" : ""; ?>">

                                <a href="<?php echo $this->url(array('controller' => 'Physician', 'action' => 'index')); ?>">

                                    For Physicians

                                </a>

                            </li>

                            <li class="<?php echo $controller == "support" ? "active" : ""; ?>">

                                <a href="<?php echo $this->url(array('controller' => 'About', 'action' => 'Support')); ?>">

                                    Support

                                </a>

                            </li>

						</ul>

						<ul class="nav pull-right">

							<li><a href="#"><i class="icon-user"></i>Log In</a></li>

							<li><a href="<?php echo $this->url(array('controller' => 'Physician', 'action' => 'register')); ?>"><i class="icon-pencil"></i>Register</a></li>

						</ul>
				
					</div>
				
				</div>

				<?php echo $this->layout()->content ?>

			</div>

		</div>

		<div id="footer">

			<div class="container">

				<div class="row margin-top-l">

					<div class="span6 pull-left">

                        <a href="<?php echo $this->url(array('controller' => 'About', 'action' => 'index')); ?>">about</a> | 

                        <a href="<?php echo $this->url(array('controller' => 'About', 'action' => 'faq')); ?>">faq</a> | 

                        <a href="<?php echo $this->url(array('controller' => 'About', 'action' => 'legal')); ?>">legal</a> | 
    
                        <a href="<?php echo $this->url(array('controller' => 'About', 'action' => 'privacy')); ?>">privacy policy</a> | 

                        <a href="<?php echo $this->url(array('controller' => 'About', 'action' => 'contact')); ?>">contact us</a> | 

                        <a href="<?php echo $this->url(array('controller' => 'About', 'action' => 'feedback')); ?>">feedback</a> <br />

						&copy; 2012 Medical Outcome Systems

					</div>

					<div class="span6 pull-right">

						<img src="/img/Medical-Outcome-Systems-Transparent.png" class="pull-right" />

					</div>


				</div>

			</div>

		</div>

        <!-- 
            PHP Version: <?php echo phpversion(); ?>

            Zend Version: <?php echo Zend_Version::getLatest(); ?>
        
        -->

	</body>

</html>
