<!--<div class="row">

    <div class="span12">

        <div class="content-inner">

            <p class="lead">		

                Need an efficient way to screen your patients before their appointment? MiniDirect can help!

            </p>

        </div>

    </div>

</div>-->

<div class="row">

    <div class="span12">

        <div>

            <div class="hero-unit">

                <h1>

                    Be your patient's hero

                </h1>

                <p>

                    Help your patients by evaluating and diagnosing them in advance of their appointments.

                </p>

                <p>

                    <a class="btn btn-primary btn-large" href="<?php echo $this->url(array('controller' => 'Physician', 'action' => 'Register')); ?>">

                        Register

                    </a>

                </p>

            </div> 

        </div>

    </div>

</div>

<div class="row">

    <div class="span12 content-outer">

        <div class="content-inner">

        

        </div>

    </div>

</div>
