<div class="row">

    <div class="span12 content-outer">

        <div class="content-inner">

            <form class="form-horizontal">

                <fieldset>

                    <legend>

                        Physician Details

                    </legend>

                    <div class="control-group">
                        
                        <label class="control-label" for="inputEmail">Physician Name</label>

                        <div class="controls">
                      
                            <input type="text" id="inputEmail" placeholder="Email" />

                        </div>

                    </div>

                    <div class="control-group">

                        <label class="control-label" for="inputPassword">Address</label>
                        
                        <div class="controls">
                        
                            <input type="text" id="inputPassword" placeholder="Address" />
                        
                        </div>
                      
                    </div>

                    <div class="control-group">

                        <label class="control-label" for="inputPassword">Address Continued</label>
                        
                        <div class="controls">
                        
                            <input type="text" id="inputPassword" placeholder="Address Continued" />
                        
                        </div>
                      
                    </div>

                    <legend>

                        Account Details

                    </legend>

                    <div class="control-group">
                        
                        <label class="control-label" for="inputEmail">Email</label>

                        <div class="controls">
                      
                            <input type="text" id="inputEmail" placeholder="Email" />

                        </div>

                    </div>

                    <div class="control-group">

                        <label class="control-label" for="inputPassword">Password</label>
                        
                        <div class="controls">
                        
                            <input type="password" id="inputPassword" placeholder="Password" />
                        
                        </div>
                      
                    </div>

                    <div class="control-group">

                        <label class="control-label" for="inputPassword">Confirm Password</label>
                        
                        <div class="controls">
                        
                            <input type="password" id="inputPassword" placeholder="Password" />
                        
                        </div>
                      
                    </div>
                      
                    <div class="control-group">
                    
                        <div class="controls">
                        
                            <button type="submit" class="btn">Register</button>

                        </div>

                    </div>

                </fieldset>

            </form>

        </div>

    </div>

</div>
