<div class="hero-unit">

	<h1>
	
		Need to find out if you're crazier than a bag of cats?	
	
	</h1>

	<p>
		
		Look no further, you crazy son of a bitch!
		
	</p>

	<p>

		<a class="btn btn-primary btn-large">

			Learn more

		</a>

	</p>

</div>

<div class="hero-unit">

	<h1>
	
		Are you a physician? Well fuck me running...
	
	</h1>

	<p>
		
		Help us get these crazy fucks off the streets!
		
	</p>

	<p>

		<a class="btn btn-primary btn-large">

			Learn more

		</a>

	</p>

</div>
